apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: searchdomains.discovery.liqo.io
spec:
  group: discovery.liqo.io
  names:
    kind: SearchDomain
    singular: searchdomain
    plural: searchdomains
    shortNames:
      - sd
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            domain:
              type: string
              description: DNS domain where to search for subscribed remote clusters
            autojoin:
              type: boolean
              description: Enable join process for retrieved clusters
          required:
            - domain
            - autojoin
        status:
          properties:
            foreignClusters:
              type: array
              description: ForeignCluster created basing on this SearchDomain