name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get -y install gcc tar wget libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev build-essential
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.26
          args: --timeout=600s -D unused,structcheck -E depguard,gosec,goimports,prealloc,godot
  fmt:
    name: Check Code Format
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Go Fmt Check
      run: |
         changed=$(go fmt ./... | wc -l)
         if [ $changed == 0 ]; then exit 0; else exit 1; fi 

